name: check

on:
  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/check.yml"
      - "interface.json"
      - "resource/**"
      - "data/**"
      - "tasks/**"
      - "pyproject.toml"
      - "requirements*.txt"
      - "**.py"
  pull_request:
    branches:
      - "**"
    paths:
      - ".github/workflows/check.yml"
      - "interface.json"
      - "resource/**"
      - "data/**"
      - "tasks/**"
      - "pyproject.toml"
      - "requirements*.txt"
      - "**.py"
  workflow_dispatch:

jobs:
  resource:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Setup uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          enable-cache: true

      - name: Run maa-checker
        run: |
          npm ci
          npx @nekosu/maa-tools check

      - name: Validate JSON Schema
        run: |
          uv sync --frozen --group dev
          uv run --frozen python tools/validate_schema.py
