name: check

on:
  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/check.yml"
      - ".node-version"
      - ".npmrc"
      - "interface.json"
      - "resource/**"
      - "data/**"
      - "tasks/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "pyproject.toml"
      - "requirements*.txt"
      - "**.py"
  pull_request:
    branches:
      - "**"
    paths:
      - ".github/workflows/check.yml"
      - ".node-version"
      - ".npmrc"
      - "interface.json"
      - "resource/**"
      - "data/**"
      - "tasks/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "pyproject.toml"
      - "requirements*.txt"
      - "**.py"
  workflow_dispatch:

jobs:
  resource:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 11.9.0

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "pnpm"

      - name: Run maa-checker
        run: |
          pnpm install --frozen-lockfile --trust-lockfile
          pnpm check:maa
